### ISSUE TITLE
File name in README.md

### ISSUE THREAD

**Issue by lucasgonze** [twitterdev/cards-player-samples#1]
The second step in the quick start is:

> Open the index.html file and 

However there is no index.html file under /player. Did you mean player/page.html, or should that be renamed to player/index.html?

**Comment by matteosistisette** [comment]
For god's sake it's been 5 months and nobody has even looked at this? And it's even the only issue that has been reported.

**Comment by teo1978** [comment]
For god's sake, in 5 months nobody has even looked at this yet? And it's the only issue that has been reported!

**Comment by ryankicks** [comment]
Sorry about this. I pushed an update; it did mean player.html. Happy to take pull requests as well.
