### ISSUE TITLE
No display, only comments !

### ISSUE THREAD

**Issue by arkxdns** [twitterdev/cards-player-samples#11]
Hello,

Maybe I missed something, but I set everything, and nothing, only the three comments :

_This page has meta tags showcasing the Twitter Player Card with a static MP4 file. The video is courtesy of @TwitterDev. 

When implemented on your own site, please ensure that all links to video are secure (use https). 

Lastly, the behavior of video playback is according to the following rules: https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/player-card_

Need help please !

**Comment by andypiper** [comment]
Apologies for the delay here - you'd be better asking for support in the [developer forums](https://twittercommunity.com) in future.

I'm unclear on what the issue you're describing is. Have you run the URL of your hosted files through the [card validator](https://cards-dev.twitter.com/validator)?

**Comment by andypiper** [comment]
Closing due to lack of follow-up. Please let us know if you are able to clarify, and ask on the developer forums linked above.
