### ISSUE TITLE
This framework is fundamentally flawed: only allows one card per html page

### ISSUE THREAD

**Issue by teo1978** [twitterdev/cards-player-samples#4]
The very essence of this whole card thing is pathetically flawed, in that one has to define the contents of a card by unique metatags in a page, meaning that one page can only contain one card.

Suppose that I have a webpage with a few posts (e.g. each post having an image, or a video).
An url like https://mydomain.com/path/to/some/page#post1 would point to a post and an url like https://mydomain.com/path/to/some/page#post2 would point to another post in the same page. Your "Cards" system doesn't allow to define a card for post1 and another card for post2, having each link work as a different card.

**Comment by ryankicks** [comment]
We understand your frustration and the inability to support hashbangs. We're tracking here:

https://twittercommunity.com/t/does-twitter-card-handle-shebang-urls/15387/8

We don't have a time for update, but please follow that report for more information.

**Comment by teo1978** [comment]
I'm not talking about fancy ajax uses of the fragment.
I'm talking a bout a simple, plain, old good #, actually pointing to a part of a simple plain HTML.
There should be no need of _escaped_fragment at all. If there is, something is very wrong about the way the cards mechanism is designed.

The idea of using meta tags in a page to define a card is ill-conceived from the very beginning.

It should be totally obvious that a "card" shouldn't be identified with the whole content of a page.
Instead of using meta tags, you should be using for example data-* attributes , which can be attached to any node. A mechanism based on data attached to nodes would allow to define a card as a node or set of nodes in a page, without the need for alternative urls to even exist. Simply retrieving the url as is would allow Twitter to scan the document and find the card.

Anyway, I filed this issue before I realized that cards need to be individually approved, which renders them completely useless (what would I use a card for if I have to wait 2 weeks for a human being to approve the content before it can be embedded in a tweet??), so who cares.

**Comment by ryankicks** [comment]
Thanks for the feedback, teo1978. We're sorry it doesn't work for you. We'll add your use case (separate from fragments) to the ticket.

**Comment by teo1978** [comment]
Actually, the post you pointed to seems to be about hashbangs, i.e. #!, I'm talking about "legitimate", plain fragments, i.e. # without a !. I don't think a conversion to ?_escaped_fragment is even to be expected here.
