### ISSUE TITLE
Not whitelisted issue

### ISSUE THREAD

**Issue by anchitjindal91** [twitterdev/cards-player-samples#6]
Hi i am using this sample code and make all  required changes as suggested in help doc. But i am getting Not whitelisted issue when i am testing it with validator. Can you please guide me what i have to do. Please see the attached and https://twitter.ethrmusic.com/player/page.html is url to my card.

![card validator twitter developers 2016-05-04 12-56-45](https://cloud.githubusercontent.com/assets/8628355/15007569/b628a31e-11f7-11e6-89f4-1f751b8de1fc.png)

Also i want to know if i want multiple card than what i have to do? need to create new html file for every card or something else please suggest ASAP. Thanks in advance

**Comment by andypiper** [comment]
Please ask questions like this in the [Cards forum](https://twittercommunity.com/c/cards) on our developer community. Thanks.
